# Generated by Django 5.2.3 on 2025-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CleaningAppliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="appliances/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, null=True, verbose_name="Характеристики"
                    ),
                ),
                (
                    "ozon_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ozon (ссылка)"
                    ),
                ),
                (
                    "wildberries_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Wildberries (ссылка)"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="appliances/pdfs/",
                        verbose_name="PDF документ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CookingAppliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="appliances/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, null=True, verbose_name="Характеристики"
                    ),
                ),
                (
                    "ozon_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ozon (ссылка)"
                    ),
                ),
                (
                    "wildberries_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Wildberries (ссылка)"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="appliances/pdfs/",
                        verbose_name="PDF документ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                ("technic", models.CharField(max_length=255, verbose_name="Техника")),
                ("description", models.TextField(verbose_name="Ответ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="infomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logo/", verbose_name="Логотип"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="appliances/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "download_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Скачать (ссылка)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_time",
                    models.CharField(max_length=255, verbose_name="Время работы"),
                ),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                ("whatsapp", models.CharField(max_length=255, verbose_name="WhatsApp")),
                ("telegram", models.CharField(max_length=255, verbose_name="Telegram")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("description", models.TextField(verbose_name="Ответ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                ("theme", models.CharField(max_length=255, verbose_name="Тема")),
                ("description", models.TextField(verbose_name="Ответ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
    ]
