# Generated by Django 5.1.7 on 2025-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaningappliance",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=500,
                null=True,
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningappliance",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=500, verbose_name="Цена"
            ),
        ),
    ]
